name: Poster Generator

on:
  schedule:
    - cron: '*/15 * * * *'  # Every 15 minutes
  workflow_dispatch:  # Allow manual trigger

jobs:
  generate-posters:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip

      - name: Install Python Dependencies
        run: |
          pip install requests
          pip install Pillow
          pip install pyzipper

      - name: Extract Protected Script
        run: |
          # Extract the password-protected zip
          ZIP_PASSWORD="${{ secrets.ZIP_PASSWORD }}" python extract_script.py

      - name: Run Poster Generator
        run: python poster.py

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Add output directory if it exists
          if [ -d "output" ]; then
            git add output/
          fi
          
          # Add matches.json if it exists
          if [ -f "matches.json" ]; then
            git add matches.json
          fi
          
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "🎨 Auto generate posters - $(date '+%Y-%m-%d %H:%M:%S')"
          fi

      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

permissions:
  contents: write
